security:
  oauth2:
    client:
      client-id: registration
      client-secret: registrationsecret
      scope: read,write
      auto-approve-scopes: '.*'

# TODO - Move to centralised config server
github:
  client:
    clientId: ${vcap.services.registration-keys.credentials.CLIENT_ID}
    clientSecret: ${vcap.services.registration-keys.credentials.CLIENT_SECRET}
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

logging:
  level:
    org.springframework.security: DEBUG
